#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : kata-runtime
Version  : 1.1.0
Release  : 10
URL      : https://github.com/kata-containers/runtime/archive/1.1.0.tar.gz
Source0  : https://github.com/kata-containers/runtime/archive/1.1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause ISC MIT MPL-2.0-no-copyleft-exception WTFPL
Requires: kata-runtime-bin
Requires: kata-runtime-config
Requires: kata-runtime-data
BuildRequires : go
Patch1: 0001-add-fake-autogen.patch
Patch2: 0002-Add-Clear-Linux-Docker-integration-for-Kata-Containe.patch

%description
[![Build Status](https://travis-ci.org/kata-containers/runtime.svg?branch=master)](https://travis-ci.org/kata-containers/runtime)
[![Build Status](http://jenkins.katacontainers.io/job/kata-containers-runtime-ubuntu-16-04-master/badge/icon)](http://jenkins.katacontainers.io/job/kata-containers-runtime-ubuntu-16-04-master/)
[![Go Report Card](https://goreportcard.com/badge/github.com/kata-containers/runtime)](https://goreportcard.com/report/github.com/kata-containers/runtime)
[![GoDoc](https://godoc.org/github.com/kata-containers/runtime?status.svg)](https://godoc.org/github.com/kata-containers/runtime)

%package bin
Summary: bin components for the kata-runtime package.
Group: Binaries
Requires: kata-runtime-data
Requires: kata-runtime-config

%description bin
bin components for the kata-runtime package.


%package config
Summary: config components for the kata-runtime package.
Group: Default

%description config
config components for the kata-runtime package.


%package data
Summary: data components for the kata-runtime package.
Group: Data

%description data
data components for the kata-runtime package.


%prep
%setup -q -n runtime-1.1.0
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533141300
%autogen --disable-static ;export GOPATH="${PWD}/gopath/" \
;mkdir -p "${GOPATH}/src/github.com/kata-containers/" \
;ln -sf "${PWD}" "${GOPATH}/src/github.com/kata-containers/runtime" \
;cd "${GOPATH}/src/github.com/kata-containers/runtime"
make  %{?_smp_mflags} QEMUPATH=/usr/bin/kata-qemu-lite-system-x86_64

%install
export SOURCE_DATE_EPOCH=1533141300
rm -rf %{buildroot}
%make_install DESTTARGET=%{buildroot}/usr/bin/kata-runtime DESTCONFIG=%{buildroot}/usr/share/defaults/kata-containers/configuration.toml QEMUPATH=/usr/bin/kata-qemu-lite-system-x86_64
## make_install_append content
sed -i -e '/^initrd =/d' %{buildroot}/usr/share/defaults/kata-containers/configuration.toml
install -m 0755 -D set-docker-default-runtime %{buildroot}/usr/bin/set-docker-default-runtime
install -m 0644 -D clearlinux.conf %{buildroot}/usr/lib/systemd/system/docker.service.d/clearlinux.conf
install -m 0644 -D 50-runtime.conf %{buildroot}/usr/lib/systemd/system/docker.service.d/50-runtime.conf
install -m 0644 -D docker-set-runtime.service %{buildroot}/usr/lib/systemd/system/docker-set-runtime.service
## make_install_append end

%files
%defattr(-,root,root,-)
/usr/local/bin/kata-collect-data.sh
/usr/local/bin/kata-runtime

%files bin
%defattr(-,root,root,-)
/usr/bin/set-docker-default-runtime

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/docker-set-runtime.service
/usr/lib/systemd/system/docker.service.d/50-runtime.conf
/usr/lib/systemd/system/docker.service.d/clearlinux.conf

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/kata-runtime
/usr/share/defaults/kata-containers/configuration.toml
